import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
            >
                <div className="flex min-h-screen">
                    {/* Sidebar */}
                    <nav className="w-56 bg-white border-r shadow-sm flex flex-col py-6 px-4">
                        <div className="mb-8">
                            <span className="text-xl font-bold text-blue-700">DADMS 2.0</span>
                        </div>
                        <ul className="flex flex-col gap-2">
                            <li>
                                <Link href="/projects" className="block px-3 py-2 rounded hover:bg-blue-100 text-gray-800 font-medium">
                                    Projects
                                </Link>
                            </li>
                            <li>
                                <Link href="/knowledge" className="block px-3 py-2 rounded hover:bg-blue-100 text-gray-800 font-medium">
                                    Knowledge
                                </Link>
                            </li>
                            <li>
                                <Link href="/llm" className="block px-3 py-2 rounded hover:bg-blue-100 text-gray-800 font-medium">
                                    LLM Playground
                                </Link>
                            </li>
                            <li>
                                <Link href="/context" className="block px-3 py-2 rounded hover:bg-blue-100 text-gray-800 font-medium">
                                    Context Manager
                                </Link>
                            </li>
                            <li>
                                <Link href="/bpmn" className="block px-3 py-2 rounded hover:bg-blue-100 text-gray-800 font-medium">
                                    BPMN Workspace
                                </Link>
                            </li>
                            <li>
                                <Link href="/process" className="block px-3 py-2 rounded hover:bg-blue-100 text-gray-800 font-medium">
                                    Process Manager
                                </Link>
                            </li>
                            <li>
                                <Link href="/thread" className="block px-3 py-2 rounded hover:bg-blue-100 text-gray-800 font-medium">
                                    Thread Manager
                                </Link>
                            </li>
                            {/* Add more navigation links here as new pages are added */}
                        </ul>
                        <div className="mt-auto pt-8 text-xs text-gray-400">
                            MVP Navigation
                        </div>
                    </nav>
                    {/* Main Content */}
                    <main className="flex-1 p-0 min-h-screen">{children}</main>
                </div>
            </body>
        </html>
    );
}
