version: '3.8'

services:
  # PostgreSQL - Primary Database
  postgres:
    image: postgres:15
    container_name: dadms-postgres
    environment:
      POSTGRES_DB: dadms
      POSTGRES_USER: dadms_user
      POSTGRES_PASSWORD: dadms_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dadms_user -d dadms" ]
      interval: 10s
      timeout: 5s
      retries: 20

  # Qdrant - Vector Database for RAG
  qdrant:
    image: qdrant/qdrant:latest
    container_name: dadms-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:6333/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20

  # Redis - Caching and Session Storage
  redis:
    image: redis:7-alpine
    container_name: dadms-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 20

  # Camunda BPM Platform - Process Engine (7.15.0 does not work)
  camunda:
    image: docker.io/camunda/camunda-bpm-platform:7.18.0
    container_name: camunda
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres:5432/dadms
      - DB_USERNAME=dadms_user
      - DB_PASSWORD=dadms_password
      - TZ=UTC
    volumes:
      - camunda_data:/camunda/data
    networks:
      - default
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/engine-rest/engine" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Ollama - Local LLM Server
  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - default
    volumes:
      - ollama_data:/root/.ollama

  # # Development Services
  # user-project-service:
  #   build: 
  #     context: ../dadms-services/user-project
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - DATABASE_URL=postgresql://dadms_user:dadms_password@postgres:5432/dadms
  #   depends_on:
  #     - postgres
  #   networks:
  #     - default

  # llm-playground-service:
  #   build: 
  #     context: ../dadms-services/llm-playground
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3006:3006"
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgresql://dadms_user:dadms_password@postgres:5432/dadms
  #     - REDIS_URL=redis://redis:6379
  #     - MINIO_ENDPOINT=minio:9000
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #     - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
  #     - OLLAMA_ENDPOINT=http://ollama:11434
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #     minio:
  #       condition: service_healthy
  #     ollama:
  #       condition: service_healthy
  #   networks:
  #     - default

  # knowledge-service:
  #   build: ./dadms-services/knowledge
  #   ports:
  #     - "3006:3006"
  #   depends_on:
  #     - postgres
  #     - qdrant

  # llm-service:
  #   build: ./dadms-services/llm
  #   ports:
  #     - "3008:3008"
  #   depends_on:
  #     - redis

  # dadms-ui:
  #   build: ./dadms-ui
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - user-project-service
  #     - knowledge-service
  #     - llm-service

  # MinIO - Object Storage for Artifacts
  minio:
    image: docker.io/minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"   # S3 API
      - "9001:9001"   # MinIO Console
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Neo4j - Graph Database for Process/Task Relationships
  neo4j:
    image: docker.io/neo4j:5.13
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/testpassword
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    volumes:
      - neo4j-data:/data
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "testpassword", "RETURN 1"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
  qdrant_data:
  redis_data:
  camunda_data:
  ollama_data:
  minio-data:
  neo4j-data:


networks:
  default:
    name: dadms-network
