name: approval_workflow
description: Specialized template for approval workflows with review and authorization steps
template: |
  You are an expert BPMN modeler specializing in approval workflows. Create a BPMN XML model for an approval process based on the following description:

  User Input: {user_input}
  Context: {context}
  Complexity Level: {complexity_level}

  Approval Workflow Requirements:
  1. Define submission and review steps
  2. Create appropriate user tasks for human interaction
  3. Include approval/rejection decision points
  4. Handle escalation paths if needed
  5. Ensure proper notification and communication flows
  6. Generate diagram information for bpmn.io compatibility

  {examples_section}

  IMPORTANT: You MUST respond with ONLY a valid JSON object. Do not include any other text, explanations, or markdown formatting outside the JSON.

  Expected JSON Response Format:
  {{
      "bpmn_xml": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\\n<bpmn:definitions xmlns:bpmn=\"http://www.omg.org/spec/BPMN/20100524/MODEL\" xmlns:bpmndi=\"http://www.omg.org/spec/BPMN/20100524/DI\" xmlns:dc=\"http://www.omg.org/spec/DD/20100524/DC\" xmlns:di=\"http://www.omg.org/spec/DD/20100524/DI\" id=\"Definitions_1\" targetNamespace=\"http://bpmn.io/schema/bpmn\">\\n  <!-- Complete BPMN XML here -->\\n</bpmn:definitions>",
      "explanation": "Detailed explanation of the approval workflow design and logic",
      "elements_created": ["startEvent", "userTask", "exclusiveGateway", "endEvent"],
      "suggestions": ["Consider adding SLA monitoring", "Include notification tasks"],
      "confidence_score": 0.9,
      "approval_steps": ["Submit Request", "Manager Review", "Final Approval"],
      "escalation_paths": ["Escalate to Director if Manager unavailable"]
  }}

  Remember: Return ONLY the JSON object, no additional text or formatting.
variables:
  - user_input
  - context
  - complexity_level
  - examples_section
examples:
  - "Create an approval workflow for expense reports"
  - "Design a process for approving purchase orders"
  - "Model a workflow for approving project proposals"
metadata:
  category: approval
  complexity: moderate
  tags: ["approval", "review", "authorization", "user_task"] 